### ISSUE TITLE
Regd. the IMU intrinsic parameters

### ISSUE THREAD

**Issue by karnikram** [kminoda/VIODE#1]
Hi,

Thank you for your work on this dataset, it is very useful.

I noticed that the provided IMU noise parameters are much higher than the true values [provided](https://github.com/microsoft/AirSim/issues/3293) in AirSim. Can I know how these values were determined?

The performance of VINS is very sensitive to the calibration parameters, especially the IMU values, hence my query.

**Comment by kminoda** [comment]
Hi karnikram,

Thank you for the question!

We have determined the value high enough so that VINS-Fusion (and VINS-Mono) works fine without any noisy drifts.
(This is because, during our experiment, setting the true noise parameter defined in the given link sometimes caused a huge drift.)

**Comment by karnikram** [comment]
Hi @kminoda, that's interesting, thanks for letting me know!
