### ISSUE TITLE
can't find the matching id in the rgb_ids.txt fot the rgbd value 

### ISSUE THREAD

**Issue by weiningwei** [kminoda/VIODE#11]
For example, in the 3_high sequence of city_day, the rgb values of keyboard pointer's pixel position are
is 144, 234,243 ; 113,119,231; 98,202, 227 in the three following figures. And the figures are the segmentation results of /segmentation topic of bagfile. But I can't match the id in the rgbd_ids.txt file.
![1669327872](https://user-images.githubusercontent.com/38557780/138644769-6142694e-c855-40cf-8871-eec0a6f3a176.jpg)
![309276595](https://user-images.githubusercontent.com/38557780/138644779-f819fb1b-cb9e-45a7-ba43-1d203b6bb72a.jpg)
![532633000](https://user-images.githubusercontent.com/38557780/138644805-786671b9-288c-4341-94ac-13115e0f89fe.jpg)
.

**Comment by kminoda** [comment]
I extracted the RGB values at those pixels on the image (1100th frame of `/cam0/segmentation` in  `city_day/3_high.bag` ), and the RGB where slightly different from the one reported above.
I loaded the image using [rosbag](http://wiki.ros.org/rosbag/Code%20API) API to load the rosbag data on Python, converting the messages using [CvBridge](http://wiki.ros.org/cv_bridge/Tutorials/ConvertingBetweenROSImagesAndOpenCVImagesPython), and then manually selecting those pixels to extract the RGB values.

It would be helpful if you would share us how you checked the RGB values (which API, apps, or libraries).

![スクリーンショット 2021-10-26 11 30 27](https://user-images.githubusercontent.com/44218668/138798814-f2620a9f-d227-4050-9fc3-d43f88794f66.png)
![スクリーンショット 2021-10-26 11 30 47](https://user-images.githubusercontent.com/44218668/138798818-f4ba3413-f3d6-4d67-8efb-8d52baf59b0c.png)
![スクリーンショット 2021-10-26 11 30 36](https://user-images.githubusercontent.com/44218668/138798822-81a5edc5-99d3-45af-afa7-53aaec403783.png)

**Comment by weiningwei** [comment]
First, I subscribe the img or segmentation topic to save the each frame segmentation resulut in some folder of computer. Then I use the python-opencv library to display it and read the rgb value.
This is my python code for converting rosbag to jpg picture. 
[read_bag_seg.txt](https://github.com/kminoda/VIODE/files/7415220/read_bag_seg.txt)

And this is my converting result of img and segmentation topic.
![1597198422 754440546-raw](https://user-images.githubusercontent.com/38557780/138811481-1a353b05-3d6a-4b8a-b15d-92f7d50157be.jpg)
![1597198422 754440546-seg](https://user-images.githubusercontent.com/38557780/138811497-57a1f635-1aca-48af-914c-b3164a1da876.jpg)

**Comment by kminoda** [comment]
Try saving the images in `png`, not `jpg`.

**Comment by weiningwei** [comment]
Yes, saving as png solved the problem, thank you for your reply.
