### ISSUE TITLE
The coordinate frame of IMU and camera

### ISSUE THREAD

**Issue by zzhh00** [kminoda/VIODE#13]
Hi,
Thanks for your contribution! I am going to test other VIO algorithms using this dataset, however I am confused about the coordinate frame of imu and camera. Can you explain the coordinate frame of each sensor please?

**Comment by zzhh00** [comment]
@kminoda

**Comment by kminoda** [comment]
Thank you for your interest!
If I recall correctly, all the sensor data is recorded in NED frame (which is a default setting of AirSim).
