### ISSUE TITLE
Unable to download the city_day.zip

### ISSUE THREAD

**Issue by nadiawangberg** [kminoda/VIODE#14]
I'm unable to download the [city_day.zip](https://zenodo.org/record/4493401#.YkP4lnVBw-I), I have attempted several times but the .zip folder is empty. I do not get this problem with city_night.zip nor with parking_lot.zip. I have 70.3GB available, so storage space should not be the issue.

**Comment by kminoda** [comment]
The link you referred to seems to be a version 2. Will you try downloading from version 3 page (the latest) instead?

**Comment by nadiawangberg** [comment]
Thanks, it works :)
