### ISSUE TITLE
Stereo camera synchronizing

### ISSUE THREAD

**Issue by hoangvietdo** [kminoda/VIODE#16]
Hello, I'm really impressed with these results.

However, I experienced non-sync stereo images while using AirSim. In particular, there is a time delay (~0.02 seconds) between the left and right camera.
Could you tell me the process of taking synced stereo images?

Thanks

**Comment by kminoda** [comment]
If I recall correctly, I used the computer vision mode in Airsim when capturing the images to ensure the time synchronization. For each ground truth pose, I paused the simulation and captured the two images from the left & right camera

**Comment by hoangvietdo** [comment]
Do you mean that we need to record the inertial pose only (IMU and odom) and run the rosbag in CV mode and capture the images?

**Comment by kminoda** [comment]
I don't think that's the only way, but yes, that's how I achieved the time synchronization.

The other method I tried was to run the simulation very slowly. But I think I still could not get the time-synchronized camera data even with the very slow simulation.

**Comment by hoangvietdo** [comment]
Yes, that is also true for me, even with slow and pause simulation, I still can't obtain sync camera data.

Is it possible for you to share the code to record the data? I know how to record the ground truth rosbag but after that, I have no idea how to run it in CV mode.

**Comment by kminoda** [comment]
I am sorry that I cannot do that. I have already graduated from the University and currently do not have access to most of my codes for generating the dataset.

But I think it was not that difficult. I think we could set a pose of the camera (in position + quaternion) in CV mode, so I wrote a python script to sequentially capture images from multiple poses sampled from the ground truth trajectory.

**Comment by hoangvietdo** [comment]
Thanks so much for your answer. I will try it!
