### ISSUE TITLE
Airsim Camera Calibration and VINS-Fusion

### ISSUE THREAD

**Issue by hoangvietdo** [kminoda/VIODE#17]
Hi,
I'm currently trying to run VINS-Fusion for my custom Airsim dataset.
The problem I faced was that I could not find any documents that explain the extrinsic parameter of the Airsim's camera (i.e., body_T_cam for VINS-Fusion).
So I just simply use your calibration matrix and this is the result:
![Screenshot from 2022-08-16 22-29-24](https://user-images.githubusercontent.com/51826956/184891643-4722e64b-f8f5-49b9-bde0-39fa3f3f456e.png)
It seems like the y-axis is flipped 180 degrees. I tried to change the extrinsic but still no luck. 
Hope you can give me some advice.
P/s: Is it possible for you to provide the settings.json of your simulation?

**Comment by kminoda** [comment]
I have already graduated from University and thus do not have access to the PC I used to generate the data at that time. So, unfortunately, I cannot provide you with the settings.json. 

If I recall correctly, I think I set the extrinsics with some config file (maybe settings.json), but I cannot recall further.
