### ISSUE TITLE
Regd. segmentation IDs

### ISSUE THREAD

**Issue by karnikram** [kminoda/VIODE#3]
The RGB to object IDs are provided in the rgb_ids.txt, but is it possible for you to provide the mapping between the different object classes and their object IDs?

**Comment by kminoda** [comment]
Thanks for the comment! 
I am sorry that the mapping for all the objects, but I have added the mapping between ID and vehicle classes.

**Comment by wjf1997** [comment]
> The RGB to object IDs are provided in the rgb_ids.txt, but is it possible for you to provide the mapping between the different object classes and their object IDs?

Hey bros,
Have you ever processed semantic image?
When I transformed the semantic image to single-channel, the value for each pixel cann't match the ID in the rgb_ids.txt.
For example, the ID value of a vehicle from single-channel image is 109 but I cann't find 109 in other .txt files. (Actually all vehicles IDs is more than 240?)
I am a rookie and looking forward to your answer.
