### ISSUE TITLE
Problem of RGB in rgb_ids.txt

### ISSUE THREAD

**Issue by wjf1997** [kminoda/VIODE#8]
rgb_ids.txt provides correspondence between IDs and RGB values in semantic image.
There are some problems.
The calculated RGB value cannot match the value in the file, so I cann't determine which object this pixel should correspond to. 
For example, in parking_high sequence, the last dynamic vehicle's calculated RGB is 108, 91, 207, 
which cannot be found in rgb_ids.txt.
Actually, IDs of six vehicles are from 245-251. In rgb_ids.txt, none of six sets of data is capable of matching 108, 91, 207.
I drew six sets of color and fail to find correspondence compared to semantic image by naked eye.

**Comment by kminoda** [comment]
Thank you for pointing it out! (and again, sorry for the late reply)
Let me investigate the problem, and hopefully give you a response in a week.

**Comment by wjf1997** [comment]
> Thank you for pointing it out! (and again, sorry for the late reply)
> Let me investigate the problem, and hopefully give you a response in a week.

Your help was very much appreciated.

**Comment by kminoda** [comment]
I've found out the problem, and updated the file with a newer version. It should be fine now, but let me know if you figure out any further problems.

Again, thank you very much for pointing this out!

**Comment by weiningwei** [comment]
Hello, I also met the same problem. For example, in the 3_high sequence of city_day, the rgb values of  keyboard pointer's pixel position are 
is 144, 234,243 ; 113,119,231; 98,202, 227 in the three following figures. But I can't match the id in the rgbd_ids.txt file.

![1669327872](https://user-images.githubusercontent.com/38557780/138560827-838fd877-3bf4-497b-9059-c05c2cf4529f.jpg)
the rgb value is 144, 234,243
![309276595](https://user-images.githubusercontent.com/38557780/138560838-d5f7bdb5-5530-4271-b561-bee3d71df843.jpg)
the rgb value is  113,119,231
![532633000](https://user-images.githubusercontent.com/38557780/138560840-f8bd934a-b9f3-4aa3-b663-95ee32a3ed52.jpg)
the rgb value is  98,202, 227
